### ISSUE TITLE
Mousing over hunter pet icon on minimap shows 'Not Collected'

### ISSUE THREAD

**Issue by repaxan** [phanx-wow/BetterBattlePetTooltip#15]
![wowscrnshot_090118_190224](https://user-images.githubusercontent.com/6520529/44951470-b4785300-ae19-11e8-9c1e-767fe0d7b51e.png)

**Comment by repaxan** [comment]
Seems to have been fixed at some point.

**Comment by armordecai** [comment]
This happens because there is a [battle pet called Crackers](https://www.wowhead.com/npc=116871/crackers). When you mouse over something on the minimap, the only information available to addons is the name, so the addon can't tell whether it's really a battle pet, or just something (like a hunter's pet) with the same name as one.
